### ISSUE TITLE
Just a Question: why not use quatnum AD in some examples?

### ISSUE THREAD

**Issue by EigenSolver** [QuantumBFS/QuAlgorithmZoo.jl#17]
Still shocked by the first example given in Yao.jl paper (which got 300,000 parameters)...

:smiley:. I am just wondering why don't you use automatic differentiation in the examples like QAOA or VQE...(I mean, something like `expect'`, and `!dispatch` maybe). 

Actually `COBYLA` is used in QAOA and VQE uses `ADAM` as optimizer, it seems like there is no calculation for gradient...

I consider AD one of the most powerful features of Yao, so confusing..

**Comment by Roger-luo** [comment]
Thanks for your question. Unfortunately, we have poor tutorials at this moment.

VQE is using AD to get the gradient. not sure why you think it's not. 
https://github.com/QuantumBFS/QuAlgorithmZoo.jl/blob/master/examples/VQE/VQE.jl#L59

if you check the date of QAOA example, it is written in pre-AD era (17 months ago).

@GiggleLiu might have some other comments.

**Comment by GiggleLiu** [comment]
> COBYLA is used in QAOA and VQE uses ADAM as optimizer

ADAM requires gradients and we have already used the gradient here. https://github.com/QuantumBFS/QuAlgorithmZoo.jl/blob/8fdef4c1d44d4a7fbaeec9ac9304448fa8cf09fa/examples/VQE/VQE.jl#L59

It should be possible to train QAOA with gradient as well, however, the parameters are shared in QAOA. One can combine Zygote and Yao to achieve parameter sharing.

https://github.com/QuantumBFS/CuYao.jl/issues/56

**Comment by GiggleLiu** [comment]
The QAOA example requires some polish though. I will look into it later.

**Comment by EigenSolver** [comment]
Yep..I noticed ADAM. By the way I just tried VQE on 4 qubits H2 (under Jordan-Weiger transformation)  with Yao and OpenFermion. (Has given a PR)

Also I tried AD on QAOA, it's so fast. (毕设看到了希望:pray: .. 感激不尽)

Think this issue can be closed now, thanks for answer.

**Comment by GiggleLiu** [comment]
Great, 希望毕业顺利！

BTW: In our example, we used the time evolution in QAOA, which is not nesseary in that case. One can use `rot(kron(Z, Z), theta)` to decompose the time evolution, so that the simulation can go faster (one need to share parameter though).

We didn't use this trick for that in real experiment, the Hamiltonian can be different and such decomposition is not always possible.
